name: CurrencyPlugin
version: 1.0
main: hu.tibor.CurrencyPlugin
author: PTibor
commands:
  currency:
    permission: currencycore.command.currency
    description: Economy Command.
  currency-player:
    permission: currencycore.admin.command.currency-player
    description: Manage players.

